version: '2'
services:
  app:
    build: .
    volumes:
      - /app/log:/app/log
      - /app/data:/app/data
      - /app/custom:/app/custom
      - /app/gitea-repositories:/app/gitea-repositories
  lb:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - /vagrant/conf/nginx.conf:/etc/nginx/conf.d/default.conf
