version: '2'
services:
  app:
    image: gitea/gitea
    volumes:
      - /app:/data
    ports:
      - "address:2022:22"
  lb:
    image: nginx
    ports:
      - "address:80:80"
    volumes:
      - /conf/gitea/nginx.conf:/etc/nginx/conf.d/default.conf
