version: '2'
services:
  gluster:
    image: gluster/gluster-centos
    privileged: true
    ports:
      - "24007:24007"
      - "2049:2049"
      - "6010:6010"
      - "6011:6011"
      - "6012:6012"
      - "38465:38465"
      - "38466:38466"
      - "38468:38468"
      - "38469:38469"
      - "49152:49152"
      - "49153:49153"
      - "49154:49154"
      - "49156:49156"
      - "49157:49157"
      - "49158:49158"
      - "49159:49159"
      - "49160:49160"
      - "49161:49161"
      - "49162:49162"
    volumes:
      - /etc/glusterfs:/etc/glusterfs
      - /var/lib/glusterd:/var/lib/glusterd
      - /var/log/glusterfs:/var/log/glusterfs
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /dev/:/dev
      - /vagrant/gluster1/hosts:/etc/hosts
      - /app:/app
      - /brick:/brick